apiVersion: v1
kind: Service
metadata:
  name: jf-service
spec:
  type: NodePort
  selector:
    app: jf
  ports:
  - name: jf
    protocol: TCP
    port: 8096
    targetPort: 8096
    nodePort: 30096
