apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin-charts.fullname" . }}
  labels:
    {{- include "jellyfin-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jellyfin-charts.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
