apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  labels:
    app: jf
    namespace: jellyfin1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jf
  template:
    metadata:
      labels:
        app: jf
    spec:
      nodeSelector:
        app: jellyfin
      volumes:
        - name: media-pv-storage
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: data-pv-storage
          persistentVolumeClaim:
            claimName: data-pv-claim
        - name: web-pv-storage
          persistentVolumeClaim:
            claimName: web-pv-claim
      containers:
        - name: linuxjellyfin-container
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
#          env:
#            - name: JELLYFIN_DATA_DIR
#              value: "/var/lib/jellyfin/data"
#            - name: JELLYFIN_CONFIG_DIR
#              value: "/media/jellyfin/config"
#            - name: JELLYFIN_CACHE_DIR
#              value: "/media/jellyfin/cache"
#            - name: JELLYFIN_WEB_DIR
#              value: "/media/jellyfin/web"
#            - name: JELLYFIN_LOG_DIR
#              value: "/media/jellyfin/logs"
          volumeMounts:
            - mountPath: "/media/jellyfin"
              name: media-pv-storage
            - mountPath: "/config"
              name: data-pv-storage
            - mountPath: "/usr/share/jellyfin/web"
              name: web-pv-storage
