apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin-charts.fullname" . }}
  labels:
    {{- include "jellyfin-charts.labels" . | nindent 4 }}
    namespace: jellyfin1
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jellyfin-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin-charts.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- with .Values.env }}
          volumeMounts:
            - mountPath: {{ .Values.mediaVolumeConfig.mountPath }}
              name: {{ .Values.mediaVolumeConfig.name }}
            - mountPath: {{ .Values.dataVolumeConfig.mountPath }}
              name: {{ .Values.dataVolumeConfig.name }}
            - mountPath: {{ .Values.webVolumeConfig.mountPath }}
              name: {{ .Values.webVolumeConfig.name }}
      volumes:
        - name: {{ .Values.mediaVolumeConfig.name }}
          persistentVolumeClaim:
            claimName: {{}}
        - name: {{ .Values.dataVolumeConfig.name }}
          persistentVolumeClaim:
            claimName: data-pv-claim
        - name: {{ .Values.webVolumeConfig.name }}
          persistentVolumeClaim:
            claimName: web-pv-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}