apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.webVolumeConfig.name }}-pv
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: {{ .Values.webVolumeConfig.storage }}
  {{- with .Values.webVolumeConfig.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostPath:
    path: {{ .Values.webVolumeConfig.hostPath }}