apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin-charts.fullname" . }}
  labels:
    {{- include "jellyfin-charts.labels" . | nindent 4 }}
    namespace: {{ .Values.namespace | default "jellyfin" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin-charts.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          ### This is for the option to change the available jellyfin directories
          ### in the container as given by https://docs.linuxserver.io/images/docker-jellyfin/#usage
          # {{- with .Values.env }}
          # env:
          #   {{- toYaml . | nindent 12 }}
          # {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.mediaVolumeConfig.mountPath }}
              name: {{ .Values.mediaVolumeConfig.name }}
            - mountPath: {{ .Values.dataVolumeConfig.mountPath }}
              name: {{ .Values.dataVolumeConfig.name }}
            ### Currently breaks the web application, testing fixes.
            # - mountPath: {{ .Values.webVolumeConfig.mountPath }}
            #   name: {{ .Values.webVolumeConfig.name }}
      volumes:
        - name: {{ .Values.mediaVolumeConfig.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mediaVolumeConfig.claimName }}
        - name: {{ .Values.dataVolumeConfig.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.dataVolumeConfig.claimName }}
        ### Intended to get session tokens and web personalization persistent
        ### across pods, currently breaks the application.
        # - name: {{ .Values.webVolumeConfig.name }}
        #   persistentVolumeClaim:
        #     claimName: {{ .Values.webVolumeConfig.claimName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}