apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/path/to/data/storage"
