apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: "800Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/path/to/media/storage"
