# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: web-pv-volume
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/MediaStorage/jellyfin-web"
