apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    {{- include .Values.dataVolumeConfig.hostPath . | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.dataVolumeConfig.storage }}