apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pv-claim
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    {{- include .Values.mediaVolumeConfig.hostPath . | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.mediaVolumeConfig.storage }}