apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    {{- include .Values.webVolumeConfig.hostPath . | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.webVolumeConfig.storage }}