apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv-volume
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/MediaStorage/jellyfin-media"