apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/MediaStorage/jellyfin-web"