apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/MediaStorage/jellyfin-web"
