# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: web-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi

